### ISSUE TITLE
 "main" java.lang.IllegalArgumentException: Unexpected value 'image/png'

### ISSUE THREAD

**Issue by youngqqcn** [nftstorage/java-client#3]
```
Exception in thread "main" java.lang.IllegalArgumentException: Unexpected value 'image/png'
	at storage.nft.model.NFT$TypeEnum.fromValue(NFT.java:83)
	at storage.nft.model.NFT$TypeEnum$Adapter.read(NFT.java:95)
	at storage.nft.model.NFT$TypeEnum$Adapter.read(NFT.java:86)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at storage.nft.JSON.deserialize(JSON.java:146)
	at storage.nft.ApiClient.deserialize(ApiClient.java:808)
	at storage.nft.ApiClient.handleResponse(ApiClient.java:1014)
	at storage.nft.ApiClient.execute(ApiClient.java:938)
	at storage.nft.api.NftStorageApi.statusWithHttpInfo(NftStorageApi.java:417)
	at storage.nft.api.NftStorageApi.status(NftStorageApi.java:395)
	at Example.main(Example.java:88)

Process finished with exit code 1
```

**Comment by plwileverts** [comment]
@dchoi27 who generally maintains this? LMK what the best path forward on this is. It's my understanding that this was autogenerated and is listed as "experimental" in the readme.

**Comment by dchoi27** [comment]
Yeah, we don't support these clients - we can close
